routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/home', 'HomeController@form');
// 	// return "Oke bgt";
// 	// return view('home');


// // Route::get('/register', 'AuthController@register');

// Route::get('/register', 'AuthController@register');
// Route::get('/welcome', 'AuthController@welcome');
// Route::POST('/welcome', 'AuthController@welcome_post');

// Route::get('/master',function(){
// 	return view('adminlte.master');
// });

// Route::get('/', function(){
// 	return view('tabel1');
// });

// Route::get('/data-tables', function(){
// 	return view('tabel2');
// });

// Route::get('/pertanyaan/create','PertanyaanController@create');
// Route::post('/pertanyaan','PertanyaanController@store');
// Route::get('/pertanyaan','PertanyaanController@index');
// Route::get('/pertanyaan/{pertanyaan_id}','PertanyaanController@show');
// Route::get('/pertanyaan/{pertanyaan_id}/edit','PertanyaanController@edit');
// Route::put('/pertanyaan/{pertanyaan_id}','PertanyaanController@update'); //update
// Route::delete('/pertanyaan/{pertanyaan_id}','PertanyaanController@destroy');


//membuat route menggunakan metode resource
Route::resource('pertanyaan','PertanyaanController'); //cek masing2 namanya di php artisan route:list

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    protected $table = "pertanyaan"; //biar nama tabel sama kaya db (dioverwrite)

    // protected $fillable = ['judul','isi']; //tabel2 mana aja yang boleh diisi
    protected $guarded = []; //semua table boleh diisi. kalau didalam [] ada diisi, berarti yang didalam [] gk boleh diisi

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AuthController extends Controller
{
    //
	public function register(){
		return view('register');
	}


	public function welcome(){
		return view('welcome');
	}

	public function welcome_post(Request $request){
		$firstname = $request->namadepan;
		$lastname = $request->namabelakang;
// dd ($lastname);

		return view('welcome', compact('firstname','lastname'));
	}





}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    //
	public function form(){
		return view('home');
	}
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Pertanyaan;

class PertanyaanController extends Controller
{
	public function create(){
		return view('pertanyaan.create');
	}

	public function store(Request $request){
	// dd($request->all());
		$request->validate([
			'judul' => 'required|unique:pertanyaan',
			'isi' => 'required'
		]);

		/*
		$query = DB::table('pertanyaan')->insert([
			"judul" => $request["judul"],
			"isi" => $request["isi"]
		]);
		*/

		/*
		// menyimpan data dengan metode save (ORM)
		$pertanyaan = new Pertanyaan;
		$pertanyaan->judul = $request["judul"];
		$pertanyaan->isi = $request["isi"];
		$pertanyaan->save();
		*/


		// menyimpan data dengan metode mass assignment. cek di file pertanyaan.php juga protected $guarded
		$pertanyaan = Pertanyaan::create([
			"judul" => $request["judul"],
			"isi" => $request["isi"]
		]);


		return redirect('/pertanyaan')->with('success','Pertanyaan Berhasil Disimpan');
		// ->with() untuk menampilkan notif sukses
	}


	public function index(){
		//$pertanyaan = DB::table('pertanyaan')->get(); //select*from pertanyaan;
		// dd($pertanyaan);
		$pertanyaan = Pertanyaan::all(); // menampilkan dengan metode model ORM

		return view('pertanyaan.index', compact('pertanyaan'));
	}

	public function show ($pertanyaan_id) {
		// $pertanyaan = DB::table('pertanyaan')->where('id', $pertanyaan_id)->first(); 
		// dd($pertanyaan);
		$pertanyaan = Pertanyaan::find($pertanyaan_id); // menampilkan dengan metode model ORM

		return view('pertanyaan.show', compact('pertanyaan'));
	}

	public function edit($pertanyaan_id){
		// $pertanyaan = DB::table('pertanyaan')->where('id', $pertanyaan_id)->first();
		$pertanyaan = Pertanyaan::find($pertanyaan_id); // menampilkan dengan metode model ORM

		return view('pertanyaan.edit', compact('pertanyaan'));

	}

	public function update($pertanyaan_id, Request $request){
		$request->validate([
			'judul' => 'required|unique:pertanyaan',
			'isi' => 'required'
		]);

		/*
		$query = DB::table('pertanyaan')
		->where('id', $pertanyaan_id)
		->update([
			'judul' => $request['judul'],
			'isi' => $request['isi']
		]);
		*/


		// Update menggunakan eloquents dengan metode mass update
		$query = Pertanyaan::where('id', $pertanyaan_id)
							->update([
								'judul' => $request['judul'],
								'isi' => $request['isi']
		]);

		return redirect('/pertanyaan')->with('success','Update Berhasil Disimpan');	
	}

	public function destroy($pertanyaan_id){
		// $query = DB::table('pertanyaan')->where('id', $pertanyaan_id)->delete();
		
		// Delete menggunakan eloquents dengan metode mass update
		Pertanyaan::destroy($pertanyaan_id);


		return redirect('/pertanyaan')->with('success','Pertanyaan Berhasil Dihapus!!!');
	}

}

resources/views/adminlte/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Blank Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('adminlte/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('adminlte/dist/css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  @stack('links')  
  
</head>
<body class="hold-transition sidebar-mini">
  <!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar -->

    @include('adminlte.partials.navbar')

    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    @include('adminlte.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->

      <!-- Main content -->
      @yield ('content')

      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
      <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.0.5
      </div>
      <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
      reserved.
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->

  <!-- jQuery -->
  <script src="{{ asset ('adminlte/plugins/jquery/jquery.min.js')}}"></script>
  <!-- Bootstrap 4 -->
  <script src="{{ asset ('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <!-- AdminLTE App -->
  <script src="{{ asset ('adminlte/dist/js/adminlte.min.js')}}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{{ asset ('adminlte/dist/js/demo.js')}}"></script>

  @stack('scripts')

<!--   <script src="{{ asset ('adminlte/plugins/datatables/jquery.dataTables.js')}}"></script>
  <script src="{{ asset ('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
  <script>
    $(function () {
      $("#example1").DataTable();
    });
  </script> -->



</body>
</html>

resources/views/adminlte/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset ('adminlte/dist/img/user1-128x128.jpg')}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset ('adminlte/dist/img/user8-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset ('adminlte/dist/img/user3-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>

resources/views/datatab.blade.php
@extends('adminlte.master')
@push('links')
<!-- <link rel="stylesheet" href="{{asset('adminlte/plugins/fontawesome-free/css/all.min.css')}}"> --> 
<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}"> 

@endpush


@push('scripts')
<script src="{{ asset ('adminlte/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{ asset ('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script>
	$(function () {
		$("#example1").DataTable();
	});
</script>
@endpush

resources/views/home.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>
<body>
	<h1> SanberBook </h1>
	<h2>Social Media Developer Santai Berkualitas</h2>
	<p>Belajar dan Berbagi agar hidup ini semakin santai berkualitas</p>
	<h3>Benefit Join di SanberBook</h3>
	<ul>
		<li>Mendapatkan motivasi dari sesama developer </li>
		<li>Sharing knowledge dari para mastah Sanber</li>
		<li>Dibuat oleh calon web developer terbaik</li>
	</ul>
	<h3>Cara Bergabung ke SanberBook</h3>
	<ol>
		<li>Mengunjungi Website ini</li>
		<li>Mendaftar di <a href="register"> Form Sign Up </a></li>
		<li>Selesai!</li>
	</ol>

</body>
</html>

resources/views/pertanyaan/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="ml-3 mt-3">
<div class="card card-primary">
	<div class="card-header">
		<h3 class="card-title">Buat Pertanyaan</h3>
	</div>
	<!-- /.card-header -->
	<!-- form start -->
	<form role="form" action="/pertanyaan" method="POST">
		@csrf
		<div class="card-body">
			<div class="form-group">
				<label for="judul">Judul</label>
				<input type="text" class="form-control" id="judul" name="judul" value="{{old('judul','')}}" placeholder="Masukan Judul Pertanyaan">
				<!-- menampilkan pesan error kalau judul udah pernah ada atau sama -->
				@error('judul')
    				<div class="alert alert-danger">{{ $message }}</div>
				@enderror
			</div>
			<div class="form-group">
				<label for="isi">Isi</label>
				<input type="text" class="form-control" id="isi" name="isi" placeholder="Isi Pertanyaan">
				@error('isi')
    				<div class="alert alert-danger">{{ $message }}</div>
				@enderror
			</div>
			
		</div>
		<!-- /.card-body -->

		<div class="card-footer">
			<button type="submit" class="btn btn-primary">Create</button>
		</div>
	</form>
</div>
</div>
@endsection

resources/views/pertanyaan/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="ml-3 mt-3">
<div class="card card-primary">
	<div class="card-header">
		<h3 class="card-title">Edit Pertanyaan {{$pertanyaan->id}}</h3>
	</div>
	<!-- /.card-header -->
	<!-- form start -->
	<form role="form" action="/pertanyaan/{{$pertanyaan->id}}" method="POST">
		@csrf
		@method('PUT')
		<div class="card-body">
			<div class="form-group">
				<label for="judul">Judul</label>
				<input type="text" class="form-control" id="judul" name="judul" value="{{old('judul',$pertanyaan->judul)}}" placeholder="Masukan Judul Pertanyaan">
				<!-- menampilkan pesan error kalau judul udah pernah ada atau sama -->
				@error('judul')
    				<div class="alert alert-danger">{{ $message }}</div>
				@enderror
			</div>
			<div class="form-group">
				<label for="isi">Isi</label>
				<input type="text" class="form-control" id="isi" name="isi" value="{{old('isi',$pertanyaan->isi)}}" placeholder="Isi Pertanyaan">
				@error('isi')
    				<div class="alert alert-danger">{{ $message }}</div>
				@enderror
			</div>
			
		</div>
		<!-- /.card-body -->

		<div class="card-footer">
			<button type="submit" class="btn btn-primary">Save</button>
		</div>
	</form>
</div>
</div>
@endsection

resources/views/pertanyaan/index.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-3">
	<div class="card">
		<div class="card-header">
			<h3 class="card-title">Daftar Pertanyaan</h3>
		</div>
		<!-- /.card-header -->
		<div class="card-body">
			<!-- untuk menampilkan kalau data berhasil disimpan -->
			@if(session('success'))
			<div class="alert alert-success">
				{{session('success')}}
			</div>
			@endif
			<!-- /. untuk menampilkan kalau data berhasil disimpan -->

			<!-- cara route pakai name --> 
			<a class="btn btn-primary mb-2" href="{{ route('pertanyaan.create')}}">Buat Pertanyaan Baru</a> 
			<!-- /. cara route pakai name -->

			<!-- cara route normal -->
			<!-- <a class="btn btn-primary mb-2" href="/pertanyaan/create">Buat Pertanyaan Baru</a> -->
			<!-- cara route normal -->
			<table class="table table-bordered">
				<thead>                  
					<tr>
						<th style="width: 10px">#</th>
						<th>Judul</th>
						<th>Pertanyaan</th>
						<th style="width: 40px">Actions</th>
					</tr>
				</thead>
				<tbody>
					<!-- isi data -->
					@forelse ($pertanyaan as $key => $pertanyaan)
					<tr>
						<td> {{ $key + 1 }} </td> <!-- nomor -->
						<td> {{ $pertanyaan->judul}} </td>
						<td> {{ $pertanyaan->isi}} </td>
						<td style = "display: flex;"> 
							
							<!-- cara route pakai name --> 
							<a href="{{ route('pertanyaan.show', ['pertanyaan' => $pertanyaan->id])}}" class="btn btn-info btn-sm">show</a>
							<a href="{{ route('pertanyaan.edit', ['pertanyaan' => $pertanyaan->id])}}" class="btn btn-default btn-sm">edit
							</a>
							<form action="{{ route('pertanyaan.destroy', ['pertanyaan' => $pertanyaan->id])}}" method="POST">
								@csrf
								@method('DELETE')
								<input type="submit" value="delete" class="btn btn-danger btn-sm">
							</form>
							<!-- /. cara route pakai name --> 

							<!-- cara route normal --> 
							<!-- <a href="/pertanyaan/{{$pertanyaan->id}}" class="btn btn-info btn-sm">show</a> -->
							<!-- <a href="/pertanyaan/{{$pertanyaan->id}}/edit" class="btn btn-default btn-sm">edit
							</a> -->
							<!-- <form action="/pertanyaan/{{$pertanyaan->id}}" method="POST">
								@csrf
								@method('DELETE')
								<input type="submit" value="delete" class="btn btn-danger btn-sm">
							</form> --> 
						</td>
					</tr>

					@empty <!-- query builder forelse empty nampilin ket kalau data kosong -->
					<tr>
						<td colspan="4" align="center"> Tidak ada data pertanyaan </td>
					</tr>
					@endforelse
				</tbody>
			</table>
		</div>
		<!-- /.card-body -->

	</div>
</div>
@endsection

resources/views/pertanyaan/show.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-3">
	<h4> {{ $pertanyaan->judul }}</h4>
	<p> {{ $pertanyaan->isi }}</p>
</div>

@endsection

resources/views/register.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Register</title>
</head>
<body>
	<form action="welcome" method="POST">
		@csrf
		<h1>Buat Account Baru!</h1>
		<h3>Sign Up Form</h3>

		<label for="">First Name:</label> <br> <br>
		<input type="text" name="namadepan"> <br> <br>
		<label for="">Last Name:</label> <br> <br>
		<input type="text" name="namabelakang"> <br> <br> 
		<label for="">Gender:</label> <br> <br>
		<input type="radio" name="jns_kelamin" value="0"> Male <br>
		<input type="radio" name="jns_kelamin" value="1"> Female <br>
		<input type="radio" name="jns_kelamin" value="2"> Other <br> <br>
		<label for="">Nationality:</label> <br><br>
		<select>
			<option>Indonesian</option>
			<option>Singaporean</option>
			<option>Malaysian</option>
			<option>Australian</option>
		</select>
		<br><br>
		<label for="">Language Spoken:</label> <br> <br>
		<input type="checkbox" name="bahasa" value="0"> Bahasa Indonesia <br>
		<input type="checkbox" name="bahasa" value="1"> English <br>
		<input type="checkbox" name="bahasa" value="2"> Other <br><br>
		<label>Bio:</label> <br> <br>
		<textarea cols="25" rows="8"></textarea> <br>
		<input type="Submit" value="Sign Up">
	</form>
</body>
</html>

resources/views/tabel1.blade.php
@extends('adminlte.master')
@section('content')

<div class="card">
  <div class="card-body">
    <table class="table table-bordered">
      <thead>                  
        <tr>
          <th style="width: 10px">#</th>
          <th>Task</th>
          <th>Progress</th>
          <th style="width: 40px">Label</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1.</td>
          <td>Update software</td>
          <td>
            <div class="progress progress-xs">
              <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
            </div>
          </td>
          <td><span class="badge bg-danger">55%</span></td>
        </tr>
        <tr>
          <td>2.</td>
          <td>Clean database</td>
          <td>
            <div class="progress progress-xs">
              <div class="progress-bar bg-warning" style="width: 70%"></div>
            </div>
          </td>
          <td><span class="badge bg-warning">70%</span></td>
        </tr>
        <tr>
          <td>3.</td>
          <td>Cron job running</td>
          <td>
            <div class="progress progress-xs progress-striped active">
              <div class="progress-bar bg-primary" style="width: 30%"></div>
            </div>
          </td>
          <td><span class="badge bg-primary">30%</span></td>
        </tr>
        <tr>
          <td>4.</td>
          <td>Fix and squish bugs</td>
          <td>
            <div class="progress progress-xs progress-striped active">
              <div class="progress-bar bg-success" style="width: 90%"></div>
            </div>
          </td>
          <td><span class="badge bg-success">90%</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
@endsection